# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddCleaning.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 140)
        Dialog.setStyleSheet("background-color: rgb(3, 125, 107)")
        self.cleaning = QtWidgets.QLineEdit(Dialog)
        self.cleaning.setGeometry(QtCore.QRect(10, 40, 181, 20))
        self.cleaning.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.cleaning.setText("")
        self.cleaning.setObjectName("cleaning")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 10, 111, 20))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 10, 101, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 111, 20))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(590, 10, 141, 20))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.OKbutton = QtWidgets.QPushButton(Dialog)
        self.OKbutton.setGeometry(QtCore.QRect(570, 90, 161, 41))
        self.OKbutton.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.OKbutton.setObjectName("OKbutton")
        self.error = QtWidgets.QLabel(Dialog)
        self.error.setGeometry(QtCore.QRect(10, 100, 541, 21))
        self.error.setStyleSheet("color: red;\n"
"font-size: 16px;\n"
"font: 16pt \"Franklin Gothic Demi\";")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.year_opened = QtWidgets.QLineEdit(Dialog)
        self.year_opened.setGeometry(QtCore.QRect(210, 40, 111, 20))
        self.year_opened.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.year_opened.setText("")
        self.year_opened.setObjectName("year_opened")
        self.phone = QtWidgets.QLineEdit(Dialog)
        self.phone.setGeometry(QtCore.QRect(340, 40, 101, 20))
        self.phone.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.dist = QtWidgets.QComboBox(Dialog)
        self.dist.setGeometry(QtCore.QRect(460, 40, 111, 22))
        self.dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.dist.setObjectName("dist")
        self.prop = QtWidgets.QComboBox(Dialog)
        self.prop.setGeometry(QtCore.QRect(590, 40, 141, 22))
        self.prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.prop.setObjectName("prop")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Название химчистки"))
        self.label_4.setText(_translate("Dialog", "Год открытия"))
        self.label_5.setText(_translate("Dialog", "Телефон"))
        self.label_6.setText(_translate("Dialog", "Район"))
        self.label_7.setText(_translate("Dialog", "Тип собственности"))
        self.OKbutton.setText(_translate("Dialog", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
