# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 1000)
        MainWindow.setStyleSheet("background-color: rgb(3, 125, 107)")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 861, 371))
        self.tableWidget.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Print_cleaning = QtWidgets.QPushButton(self.centralwidget)
        self.Print_cleaning.setGeometry(QtCore.QRect(30, 491, 151, 23))
        self.Print_cleaning.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_cleaning.setObjectName("Print_cleaning")
        self.Print_customer = QtWidgets.QPushButton(self.centralwidget)
        self.Print_customer.setGeometry(QtCore.QRect(30, 521, 151, 23))
        self.Print_customer.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_customer.setObjectName("Print_customer")
        self.Print_service = QtWidgets.QPushButton(self.centralwidget)
        self.Print_service.setGeometry(QtCore.QRect(230, 551, 151, 23))
        self.Print_service.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_service.setObjectName("Print_service")
        self.Print_cl_sv = QtWidgets.QPushButton(self.centralwidget)
        self.Print_cl_sv.setGeometry(QtCore.QRect(30, 581, 151, 23))
        self.Print_cl_sv.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_cl_sv.setObjectName("Print_cl_sv")
        self.Print_dist = QtWidgets.QPushButton(self.centralwidget)
        self.Print_dist.setGeometry(QtCore.QRect(230, 491, 151, 23))
        self.Print_dist.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_dist.setObjectName("Print_dist")
        self.Print_rate = QtWidgets.QPushButton(self.centralwidget)
        self.Print_rate.setGeometry(QtCore.QRect(230, 521, 151, 23))
        self.Print_rate.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_rate.setObjectName("Print_rate")
        self.Print_prop = QtWidgets.QPushButton(self.centralwidget)
        self.Print_prop.setGeometry(QtCore.QRect(230, 581, 151, 23))
        self.Print_prop.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_prop.setObjectName("Print_prop")
        self.Print_order = QtWidgets.QPushButton(self.centralwidget)
        self.Print_order.setGeometry(QtCore.QRect(30, 551, 151, 23))
        self.Print_order.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Print_order.setObjectName("Print_order")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 430, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 32px;\n"
"font: \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Q_3_8_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_8.setGeometry(QtCore.QRect(430, 600, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Q_3_8_8.setFont(font)
        self.Q_3_8_8.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_8.setObjectName("Q_3_8_8")
        self.Q_3_8_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_9.setGeometry(QtCore.QRect(430, 640, 401, 31))
        self.Q_3_8_9.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_9.setObjectName("Q_3_8_9")
        self.Q_3_8_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_10.setGeometry(QtCore.QRect(430, 680, 401, 31))
        self.Q_3_8_10.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_10.setObjectName("Q_3_8_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 510, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Q_3_8_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_7.setGeometry(QtCore.QRect(670, 550, 41, 31))
        self.Q_3_8_7.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_7.setObjectName("Q_3_8_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 380, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 32px;\n"
"font: \"Arial Black\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Q_3_8_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_1.setGeometry(QtCore.QRect(450, 470, 41, 31))
        self.Q_3_8_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_1.setObjectName("Q_3_8_1")
        self.Q_3_8_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_4.setGeometry(QtCore.QRect(780, 470, 41, 31))
        self.Q_3_8_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_4.setObjectName("Q_3_8_4")
        self.Q_3_8_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_6.setGeometry(QtCore.QRect(560, 550, 41, 31))
        self.Q_3_8_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_6.setObjectName("Q_3_8_6")
        self.Q_3_8_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_5.setGeometry(QtCore.QRect(450, 550, 41, 31))
        self.Q_3_8_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_5.setObjectName("Q_3_8_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 429, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"font: \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Q_3_8_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_3.setGeometry(QtCore.QRect(670, 470, 41, 31))
        self.Q_3_8_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_3.setObjectName("Q_3_8_3")
        self.Q_3_8_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_8_2.setGeometry(QtCore.QRect(560, 470, 41, 31))
        self.Q_3_8_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_8_2.setObjectName("Q_3_8_2")
        self.Q_3_9_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_1.setGeometry(QtCore.QRect(430, 720, 401, 31))
        self.Q_3_9_1.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_1.setObjectName("Q_3_9_1")
        self.Q_3_9_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_3.setGeometry(QtCore.QRect(430, 800, 401, 31))
        self.Q_3_9_3.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_3.setObjectName("Q_3_9_3")
        self.Q_3_9_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_2.setGeometry(QtCore.QRect(430, 760, 401, 31))
        self.Q_3_9_2.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_2.setObjectName("Q_3_9_2")
        self.Q_3_9_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_4.setGeometry(QtCore.QRect(430, 840, 401, 31))
        self.Q_3_9_4.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_4.setObjectName("Q_3_9_4")
        self.Q_3_9_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_6.setGeometry(QtCore.QRect(430, 920, 401, 31))
        self.Q_3_9_6.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_6.setObjectName("Q_3_9_6")
        self.Q_3_9_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Q_3_9_5.setGeometry(QtCore.QRect(430, 880, 401, 31))
        self.Q_3_9_5.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Q_3_9_5.setObjectName("Q_3_9_5")
        self.add_client = QtWidgets.QPushButton(self.centralwidget)
        self.add_client.setGeometry(QtCore.QRect(30, 860, 351, 41))
        self.add_client.setStyleSheet("font-size: 18px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_client.setObjectName("add_client")
        self.add_order = QtWidgets.QPushButton(self.centralwidget)
        self.add_order.setGeometry(QtCore.QRect(30, 910, 351, 41))
        self.add_order.setStyleSheet("font-size: 18px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.add_order.setObjectName("add_order")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 380, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"font: \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Курсовая работа БД Мамчур ПИ-20а"))
        self.Print_cleaning.setText(_translate("MainWindow", "Химчистки"))
        self.Print_customer.setText(_translate("MainWindow", "Заказчики"))
        self.Print_service.setText(_translate("MainWindow", "Услуги"))
        self.Print_cl_sv.setText(_translate("MainWindow", "Услуги химчистки"))
        self.Print_dist.setText(_translate("MainWindow", "Районы"))
        self.Print_rate.setText(_translate("MainWindow", "Тарифы"))
        self.Print_prop.setText(_translate("MainWindow", "Тип собственности"))
        self.Print_order.setText(_translate("MainWindow", "Заказы"))
        self.label.setText(_translate("MainWindow", "Просмотр таблиц"))
        self.Q_3_8_8.setText(_translate("MainWindow", "левое внешнее соединение"))
        self.Q_3_8_9.setText(_translate("MainWindow", "правое внешнее соединение"))
        self.Q_3_8_10.setText(_translate("MainWindow", "запрос на запросе по принципу левого соединения "))
        self.label_5.setText(_translate("MainWindow", "симметричное внутреннее соединение без условия "))
        self.Q_3_8_7.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "Выполнить запрос"))
        self.Q_3_8_1.setText(_translate("MainWindow", "1"))
        self.Q_3_8_4.setText(_translate("MainWindow", "4"))
        self.Q_3_8_6.setText(_translate("MainWindow", "2"))
        self.Q_3_8_5.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "симметричное внутреннее соединение с условием"))
        self.Q_3_8_3.setText(_translate("MainWindow", "3"))
        self.Q_3_8_2.setText(_translate("MainWindow", "2"))
        self.Q_3_9_1.setText(_translate("MainWindow", "итоговый запрос без условия "))
        self.Q_3_9_3.setText(_translate("MainWindow", "итоговый запрос с условием на группы"))
        self.Q_3_9_2.setText(_translate("MainWindow", "итоговый запрос с условием на данные"))
        self.Q_3_9_4.setText(_translate("MainWindow", "итоговый запрос с условием на данные и на группы "))
        self.Q_3_9_6.setText(_translate("MainWindow", "запрос с подзапросом "))
        self.Q_3_9_5.setText(_translate("MainWindow", "запрос на запросе по принципу итогового запроса "))
        self.add_client.setText(_translate("MainWindow", "Добавить заказчика"))
        self.add_order.setText(_translate("MainWindow", "Добавить заказ"))
        self.label_2.setText(_translate("MainWindow", "Вы работаете в режиме клиента!"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
